import pygame
import sys

# Initialize Pygame
pygame.init()

# Set up the screen dimensions
WIDTH, HEIGHT = 800, 600
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Race to the Finish Line")

# Define colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

# Define the player properties
player_width = 50
player_height = 50
player_x = 100
player_y = HEIGHT // 2 - player_height // 2
player_speed = 5

# Define the finish line properties
finish_line_x = WIDTH - 150
finish_line_width = 10
finish_line_height = HEIGHT

# Set up the font
font = pygame.font.Font(None, 74)

# Game loop
def game_loop():
    global player_x, player_y

    clock = pygame.time.Clock()
    running = True
    while running:
        screen.fill(WHITE)

        # Draw finish line
        pygame.draw.rect(screen, GREEN, (finish_line_x, 0, finish_line_width, finish_line_height))

        # Draw the player (a simple rectangle)
        pygame.draw.rect(screen, BLUE, (player_x, player_y, player_width, player_height))

        # Check for events
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        # Handle key press for movement
        keys = pygame.key.get_pressed()
        if keys[pygame.K_UP] and player_y > 0:
            player_y -= player_speed
        if keys[pygame.K_DOWN] and player_y < HEIGHT - player_height:
            player_y += player_speed
        if keys[pygame.K_LEFT] and player_x > 0:
            player_x -= player_speed
        if keys[pygame.K_RIGHT] and player_x < WIDTH - player_width:
            player_x += player_speed

        # Check if the player has reached the finish line
        if player_x + player_width >= finish_line_x:
            victory_text = font.render("You Win!", True, RED)
            screen.blit(victory_text, (WIDTH // 2 - victory_text.get_width() // 2, HEIGHT // 2 - victory_text.get_height() // 2))
            pygame.display.update()
            pygame.time.wait(2000)  # Wait for 2 seconds before closing
            running = False

        pygame.display.update()
        clock.tick(60)  # Set frame rate to 60 FPS

    pygame.quit()
    sys.exit()

if __name__ == "__main__":
    game_loop()
